/* eslint-disable */
/**
 * Generated by convex dev. DO NOT EDIT.
 *
 * This is a stub file for development before running `npx convex dev`.
 * It will be overwritten when Convex generates the real types.
 */

import { anyApi } from "convex/server";

export const api: typeof anyApi = anyApi;
export const internal: typeof anyApi = anyApi;
