/* eslint-disable */
/**
 * Generated by convex dev. DO NOT EDIT.
 *
 * This is a stub file for development before running `npx convex dev`.
 * It will be overwritten when Convex generates the real types.
 */

import type { GenericDataModel } from "convex/server";
import type { GenericId } from "convex/values";

export type DataModel = GenericDataModel;
export type Id<T extends string> = GenericId<T>;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Doc<_T extends string> = any;
