/* eslint-disable */
/**
 * Generated by convex dev. DO NOT EDIT.
 *
 * This is a stub file for development before running `npx convex dev`.
 * It will be overwritten when Convex generates the real types.
 */

import type { GenericDataModel } from "convex/server";

export type DataModel = GenericDataModel;
