/* eslint-disable */
/**
 * Generated by convex dev. DO NOT EDIT.
 *
 * This is a stub file for development before running `npx convex dev`.
 * It will be overwritten when Convex generates the real types.
 */

import {
  GenericQueryCtx,
  GenericMutationCtx,
  GenericActionCtx,
  GenericDatabaseReader,
  GenericDatabaseWriter,
  FunctionReference,
  anyApi,
} from "convex/server";
import type { DataModel } from "./dataModel";

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;
export type DatabaseReader = GenericDatabaseReader<DataModel>;
export type DatabaseWriter = GenericDatabaseWriter<DataModel>;

import {
  queryGeneric,
  mutationGeneric,
  actionGeneric,
  internalQueryGeneric,
  internalMutationGeneric,
  internalActionGeneric,
  httpActionGeneric,
} from "convex/server";

export const query = queryGeneric as typeof queryGeneric;
export const mutation = mutationGeneric as typeof mutationGeneric;
export const action = actionGeneric as typeof actionGeneric;
export const internalQuery = internalQueryGeneric as typeof internalQueryGeneric;
export const internalMutation = internalMutationGeneric as typeof internalMutationGeneric;
export const internalAction = internalActionGeneric as typeof internalActionGeneric;
export const httpAction = httpActionGeneric as typeof httpActionGeneric;
