/**
 * Default Hualien crop seed data.
 * These 15 crops represent the original region-specific crop database.
 *
 * Usage:
 *   import { seedDefaultCrops } from '@/server/db/seed/crops'
 *   await seedDefaultCrops(db, farmId)
 *
 * Or run directly:
 *   bun scripts/seed-crops.ts
 */

import type { InferInsertModel } from 'drizzle-orm'
import { crops } from '@/server/db/schema'
import { db } from '@/server/db'

type CropInsert = Omit<InferInsertModel<typeof crops>, 'id' | 'farmId' | 'createdAt' | 'updatedAt'>

/**
 * Seed the 15 default Hualien crops for a given farm.
 * Safe to call multiple times — duplicates may be inserted if called
 * concurrently, but that's acceptable for default crops.
 */
export async function seedDefaultCrops(farmId: string) {
  const rows = defaultCrops.map((crop) => ({ ...crop, farmId }))
  await db.insert(crops).values(rows)
}

const categoryMap = {
  根莖類: 'root_vegetables',
  瓜果類: 'gourds_melons',
  葉菜類: 'leafy_vegetables',
  辛香料: 'aromatics',
  水果類: 'fruits',
  茄果類: 'solanaceae',
} as const

const waterMap = {
  少量: 'minimal',
  適量: 'moderate',
  大量: 'abundant',
} as const

const sunlightMap = {
  全日照: 'full_sun',
  半日照: 'partial_shade',
  耐陰: 'shade_tolerant',
} as const

const resistanceMap = {
  低: 'low',
  中: 'medium',
  高: 'high',
} as const

export const defaultCrops: CropInsert[] = [
  {
    name: '地瓜',
    emoji: '🍠',
    color: '#c2410c',
    category: categoryMap['根莖類'],
    plantingMonths: [2, 3, 4, 8, 9],
    harvestMonths: [6, 7, 8, 12, 1],
    growthDays: 120,
    spacingRowCm: 80,
    spacingPlantCm: 30,
    water: waterMap['適量'],
    sunlight: sunlightMap['全日照'],
    tempMin: 20,
    tempMax: 30,
    fertilizerIntervalDays: 30,
    needsPruning: false,
    pestControl: ['甘藷蟻象：使用性費洛蒙誘殺', '蟻象幼蟲：培土覆蓋薯塊', '葉蟎：噴施礦物油乳劑'],
    typhoonResistance: resistanceMap['高'],
    hualienNotes: '花蓮土壤排水良好適合種植，秋作品質較佳。颱風後可快速恢復生長。',
    isDefault: true,
  },
  {
    name: '南瓜',
    emoji: '🎃',
    color: '#ea580c',
    category: categoryMap['瓜果類'],
    plantingMonths: [2, 3, 4, 8, 9],
    harvestMonths: [5, 6, 7, 11, 12],
    growthDays: 90,
    spacingRowCm: 200,
    spacingPlantCm: 150,
    water: waterMap['適量'],
    sunlight: sunlightMap['全日照'],
    tempMin: 18,
    tempMax: 32,
    fertilizerIntervalDays: 14,
    needsPruning: true,
    pruningMonths: [3, 4, 5, 9, 10],
    pestControl: ['白粉病：通風管理、避免葉面澆水', '瓜實蠅：套袋保護果實', '蚜蟲：黃色黏紙誘捕'],
    typhoonResistance: resistanceMap['低'],
    hualienNotes: '花蓮春作為主，需搭設棚架。颱風季前務必提前採收或加強固定藤蔓。',
    isDefault: true,
  },
  {
    name: '絲瓜',
    emoji: '🥒',
    color: '#16a34a',
    category: categoryMap['瓜果類'],
    plantingMonths: [3, 4, 5],
    harvestMonths: [5, 6, 7, 8, 9],
    growthDays: 60,
    spacingRowCm: 150,
    spacingPlantCm: 100,
    water: waterMap['大量'],
    sunlight: sunlightMap['全日照'],
    tempMin: 22,
    tempMax: 35,
    fertilizerIntervalDays: 14,
    needsPruning: true,
    pruningMonths: [5, 6, 7, 8],
    pestControl: ['瓜實蠅：誘殺器設置', '露菌病：避免傍晚澆水', '銀葉粉蝨：懸掛黃色黏紙'],
    typhoonResistance: resistanceMap['低'],
    hualienNotes: '花蓮夏季高溫多濕，絲瓜生長快速。棚架需加強抗風能力。',
    isDefault: true,
  },
  {
    name: '苦瓜',
    emoji: '🥬',
    color: '#65a30d',
    category: categoryMap['瓜果類'],
    plantingMonths: [3, 4, 5],
    harvestMonths: [6, 7, 8, 9],
    growthDays: 70,
    spacingRowCm: 150,
    spacingPlantCm: 80,
    water: waterMap['適量'],
    sunlight: sunlightMap['全日照'],
    tempMin: 20,
    tempMax: 35,
    fertilizerIntervalDays: 14,
    needsPruning: true,
    pruningMonths: [5, 6, 7, 8],
    pestControl: ['瓜實蠅：含毒甲基丁香油誘殺', '白粉病：保持通風、降低密度', '薊馬：藍色黏紙誘捕'],
    typhoonResistance: resistanceMap['低'],
    hualienNotes: '花蓮山苦瓜品質優良，適合有機栽培。建議搭設堅固棚架。',
    isDefault: true,
  },
  {
    name: '空心菜',
    emoji: '🥬',
    color: '#15803d',
    category: categoryMap['葉菜類'],
    plantingMonths: [3, 4, 5, 6, 7, 8, 9],
    harvestMonths: [4, 5, 6, 7, 8, 9, 10],
    growthDays: 30,
    spacingRowCm: 20,
    spacingPlantCm: 15,
    water: waterMap['大量'],
    sunlight: sunlightMap['全日照'],
    tempMin: 25,
    tempMax: 35,
    fertilizerIntervalDays: 10,
    needsPruning: false,
    pestControl: ['斜紋夜蛾：使用蘇力菌防治', '白鏽病：避免連作、保持排水', '蚜蟲：噴施苦楝油'],
    typhoonResistance: resistanceMap['中'],
    hualienNotes: '花蓮水源充沛，適合大面積種植。可連續採收多次。颱風後恢復力強。',
    isDefault: true,
  },
  {
    name: '小白菜',
    emoji: '🥬',
    color: '#22c55e',
    category: categoryMap['葉菜類'],
    plantingMonths: [9, 10, 11, 12, 1, 2, 3],
    harvestMonths: [10, 11, 12, 1, 2, 3, 4],
    growthDays: 25,
    spacingRowCm: 20,
    spacingPlantCm: 15,
    water: waterMap['適量'],
    sunlight: sunlightMap['半日照'],
    tempMin: 15,
    tempMax: 25,
    fertilizerIntervalDays: 10,
    needsPruning: false,
    pestControl: ['小菜蛾：蘇力菌噴施', '黃條葉蚤：覆蓋防蟲網', '根瘤病：輪作管理'],
    typhoonResistance: resistanceMap['低'],
    hualienNotes: '秋冬為主要產期，花蓮冬季溫暖適合生長。夏季高溫需遮陰處理。',
    isDefault: true,
  },
  {
    name: '蔥',
    emoji: '🧅',
    color: '#4ade80',
    category: categoryMap['辛香料'],
    plantingMonths: [9, 10, 11, 12, 1, 2],
    harvestMonths: [11, 12, 1, 2, 3, 4],
    growthDays: 60,
    spacingRowCm: 20,
    spacingPlantCm: 10,
    water: waterMap['適量'],
    sunlight: sunlightMap['全日照'],
    tempMin: 15,
    tempMax: 25,
    fertilizerIntervalDays: 14,
    needsPruning: false,
    pestControl: ['甜菜夜蛾：性費洛蒙誘殺', '銹病：避免密植、保持通風', '薊馬：藍色黏紙'],
    typhoonResistance: resistanceMap['低'],
    hualienNotes: '花蓮三星蔥品質聞名，秋冬種植品質最佳。夏季容易軟腐需注意排水。',
    isDefault: true,
  },
  {
    name: '薑',
    emoji: '🫚',
    color: '#ca8a04',
    category: categoryMap['根莖類'],
    plantingMonths: [2, 3, 4],
    harvestMonths: [8, 9, 10, 11],
    growthDays: 180,
    spacingRowCm: 40,
    spacingPlantCm: 25,
    water: waterMap['適量'],
    sunlight: sunlightMap['半日照'],
    tempMin: 20,
    tempMax: 30,
    fertilizerIntervalDays: 21,
    needsPruning: false,
    pestControl: ['軟腐病：避免積水、種薑消毒', '紋枯病：降低密度', '薑螟蛾：清除被害莖'],
    typhoonResistance: resistanceMap['中'],
    hualienNotes: '花蓮山區種薑品質優良，需注意排水。建議覆蓋稻草保濕並抑制雜草。',
    isDefault: true,
  },
  {
    name: '香蕉',
    emoji: '🍌',
    color: '#eab308',
    category: categoryMap['水果類'],
    plantingMonths: [2, 3, 4, 5],
    harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    growthDays: 365,
    spacingRowCm: 300,
    spacingPlantCm: 250,
    water: waterMap['大量'],
    sunlight: sunlightMap['全日照'],
    tempMin: 20,
    tempMax: 35,
    fertilizerIntervalDays: 30,
    needsPruning: true,
    pruningMonths: [3, 4, 5, 6, 7, 8, 9, 10],
    pestControl: ['香蕉黃葉病：使用健康種苗', '花薊馬：套袋保護', '象鼻蟲：清除殘株'],
    typhoonResistance: resistanceMap['低'],
    hualienNotes: '花蓮為重要香蕉產區，颱風是最大威脅。建議種植矮性品種並做好防風措施。',
    isDefault: true,
  },
  {
    name: '木瓜',
    emoji: '🫒',
    color: '#f97316',
    category: categoryMap['水果類'],
    plantingMonths: [3, 4, 5],
    harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    growthDays: 270,
    spacingRowCm: 250,
    spacingPlantCm: 200,
    water: waterMap['適量'],
    sunlight: sunlightMap['全日照'],
    tempMin: 22,
    tempMax: 35,
    fertilizerIntervalDays: 14,
    needsPruning: false,
    pestControl: ['輪點病毒：種植抗病品種', '果實蠅：套袋或誘殺', '紅蜘蛛：噴水沖洗葉背'],
    typhoonResistance: resistanceMap['低'],
    hualienNotes: '花蓮木瓜甜度高，但極怕颱風。建議種植矮化品種，颱風前採收青木瓜。',
    isDefault: true,
  },
  {
    name: '番茄',
    emoji: '🍅',
    color: '#dc2626',
    category: categoryMap['茄果類'],
    plantingMonths: [9, 10, 11],
    harvestMonths: [12, 1, 2, 3, 4],
    growthDays: 90,
    spacingRowCm: 60,
    spacingPlantCm: 40,
    water: waterMap['適量'],
    sunlight: sunlightMap['全日照'],
    tempMin: 18,
    tempMax: 28,
    fertilizerIntervalDays: 14,
    needsPruning: true,
    pruningMonths: [10, 11, 12, 1, 2, 3],
    pestControl: ['晚疫病：避免葉面濕潤過久', '番茄斑潛蠅：黃色黏紙', '青枯病：輪作、嫁接抗病砧木'],
    typhoonResistance: resistanceMap['低'],
    hualienNotes: '花蓮秋冬種植品質佳，日夜溫差大有助糖度累積。需搭設支架防倒伏。',
    isDefault: true,
  },
  {
    name: '辣椒',
    emoji: '🌶️',
    color: '#ef4444',
    category: categoryMap['茄果類'],
    plantingMonths: [2, 3, 4, 8, 9],
    harvestMonths: [5, 6, 7, 8, 11, 12],
    growthDays: 80,
    spacingRowCm: 50,
    spacingPlantCm: 35,
    water: waterMap['少量'],
    sunlight: sunlightMap['全日照'],
    tempMin: 20,
    tempMax: 30,
    fertilizerIntervalDays: 14,
    needsPruning: true,
    pruningMonths: [4, 5, 6, 9, 10, 11],
    pestControl: ['炭疽病：避免密植、通風良好', '蚜蟲：噴施苦楝油', '疫病：排水良好、輪作'],
    typhoonResistance: resistanceMap['中'],
    hualienNotes: '花蓮辣椒風味獨特，春秋兩季皆可種植。注意排水以防根部病害。',
    isDefault: true,
  },
  {
    name: '茄子',
    emoji: '🍆',
    color: '#7c3aed',
    category: categoryMap['茄果類'],
    plantingMonths: [2, 3, 4, 8, 9],
    harvestMonths: [5, 6, 7, 8, 11, 12],
    growthDays: 75,
    spacingRowCm: 60,
    spacingPlantCm: 45,
    water: waterMap['適量'],
    sunlight: sunlightMap['全日照'],
    tempMin: 22,
    tempMax: 32,
    fertilizerIntervalDays: 14,
    needsPruning: true,
    pruningMonths: [4, 5, 6, 7, 9, 10, 11],
    pestControl: ['二點葉蟎：噴水沖洗', '茄黃萎病：嫁接抗病砧木', '茄螟蛾：摘除被害果'],
    typhoonResistance: resistanceMap['低'],
    hualienNotes: '花蓮茄子品質優良，需搭設支架。高溫期注意紅蜘蛛為害。',
    isDefault: true,
  },
  {
    name: '高麗菜',
    emoji: '🥬',
    color: '#86efac',
    category: categoryMap['葉菜類'],
    plantingMonths: [8, 9, 10, 11],
    harvestMonths: [11, 12, 1, 2, 3],
    growthDays: 90,
    spacingRowCm: 50,
    spacingPlantCm: 40,
    water: waterMap['適量'],
    sunlight: sunlightMap['全日照'],
    tempMin: 15,
    tempMax: 25,
    fertilizerIntervalDays: 14,
    needsPruning: false,
    pestControl: ['紋白蝶：防蟲網覆蓋', '小菜蛾：蘇力菌防治', '黑腐病：輪作、排水管理'],
    typhoonResistance: resistanceMap['低'],
    hualienNotes: '花蓮秋冬高麗菜品質好，但需注意秋颱影響。建議9月後定植較安全。',
    isDefault: true,
  },
  {
    name: '芥菜',
    emoji: '🥬',
    color: '#059669',
    category: categoryMap['葉菜類'],
    plantingMonths: [9, 10, 11],
    harvestMonths: [12, 1, 2],
    growthDays: 60,
    spacingRowCm: 40,
    spacingPlantCm: 30,
    water: waterMap['適量'],
    sunlight: sunlightMap['全日照'],
    tempMin: 15,
    tempMax: 22,
    fertilizerIntervalDays: 14,
    needsPruning: false,
    pestControl: ['蚜蟲：苦楝油防治', '黃條葉蚤：輪作管理', '軟腐病：避免積水'],
    typhoonResistance: resistanceMap['低'],
    hualienNotes: '花蓮客家庄傳統作物，適合製作酸菜、福菜。冬季種植品質最佳。',
    isDefault: true,
  },
]
